export const ROUTES = {
    TEXT_FIELD: '/text-field',
    AUTOCOMPLETE: '/autocomplete',
    CHECKBOX: '/checkbox',
    SWITCH: '/switch',
    RADIO_GROUP: '/radio-group',
    BUTTON: '/button',
    LINK: '/link',
    DROPDOWN: '/dropdown',
    PAGINATION: '/pagination',
    STAR_RATING: '/start-rating',
    SLIDER: '/slider',
    ACCORDION: '/accordion',
    BACKDROP: '/backdrop',
    ASIDE_MENU: '/aside-menu',
}